kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devops-three-node-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 30443
    hostPort: 443
- role: worker
- role: worker
